import { useEffect } from "react";
import { Link } from "react-router-dom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function Terms() {
    useEffect(() => {
        document.title = "Terms & Conditions — ResumeForge AI";
        return () => { document.title = "ResumeForge AI — ATS-Friendly Resume Builder"; };
    }, []);

    return (
        <div className="min-h-screen bg-stone-50" data-testid="terms-page">
            <Navbar />
            <article className="max-w-3xl mx-auto px-6 lg:px-10 pt-16 pb-16">
                <div className="text-[10px] font-mono uppercase tracking-[0.3em] text-amber-600 mb-3">Legal</div>
                <h1 className="font-display text-4xl sm:text-5xl tracking-tighter font-bold leading-[1.05]">Terms & Conditions</h1>
                <p className="text-sm text-stone-500 mt-3 font-mono">Last updated: February 10, 2026</p>

                <div className="mt-10 prose prose-stone max-w-none space-y-8 text-stone-800 leading-relaxed">
                    <Block h="1. Acceptance of terms">
                        By accessing or using ResumeForge AI (the "Service"), you agree to these Terms & Conditions. If you do not agree, do not use the Service.
                    </Block>

                    <Block h="2. The Service">
                        ResumeForge AI is a web tool that helps you build, edit, preview, and download resumes and cover letters, with optional AI-assisted writing features. Some features require a free account.
                    </Block>

                    <Block h="3. Eligibility">
                        You must be at least 13 years old (or the age of digital consent in your jurisdiction) to use ResumeForge AI. By using the Service, you confirm that you meet this requirement.
                    </Block>

                    <Block h="4. Your account">
                        You are responsible for keeping your password confidential and for all activity that occurs under your account. Notify us immediately at <a href="mailto:support@resumeforge.ai" className="text-[#002FA7] hover:underline">support@resumeforge.ai</a> of any unauthorised use.
                    </Block>

                    <Block h="5. Acceptable use">
                        <p>You agree NOT to:</p>
                        <ul className="list-disc ml-6 mt-2 space-y-1">
                            <li>Use the Service to fabricate fraudulent credentials, qualifications, or experience.</li>
                            <li>Upload or generate content that is illegal, defamatory, hateful, or violates third-party rights.</li>
                            <li>Reverse-engineer, scrape, or attempt to extract source code from the Service.</li>
                            <li>Use the Service to send spam, malware, or to circumvent rate limits.</li>
                            <li>Resell or sublicense the Service without our written permission.</li>
                        </ul>
                        <p className="mt-2">We may suspend or terminate accounts that violate these rules.</p>
                    </Block>

                    <Block h="6. Your content">
                        You retain ownership of all content you create with ResumeForge AI (resumes, cover letters, etc.). You grant us a limited, non-exclusive licence to host, process, and display your content solely to operate and improve the Service. We do not sell your content. We do not use your content to train AI models.
                    </Block>

                    <Block h="7. AI features">
                        AI suggestions are generated by third-party language models (Anthropic Claude). They are best-effort drafts to inspire your own writing. <span className="font-semibold">You are solely responsible</span> for verifying accuracy and ensuring everything in your resume is truthful before submitting it to a recruiter.
                    </Block>

                    <Block h="8. Free service & ads">
                        ResumeForge AI is currently free. The Service may display advertisements, affiliate links, or sponsored content to support operations. We may introduce premium features or paid tiers in the future; if we do, existing free features will be communicated clearly in advance.
                    </Block>

                    <Block h="9. Disclaimers">
                        The Service is provided "as is" and "as available." We do not guarantee that AI suggestions will land you an interview, that your resume will pass every Applicant Tracking System, or that the Service will be uninterrupted or error-free. To the fullest extent permitted by law, we disclaim all warranties, express or implied.
                    </Block>

                    <Block h="10. Limitation of liability">
                        To the fullest extent permitted by law, ResumeForge AI and its team shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of the Service. Our aggregate liability for any claim relating to the Service shall not exceed the amount you paid us in the 12 months preceding the claim (if any).
                    </Block>

                    <Block h="11. Termination">
                        You may stop using the Service and delete your account at any time from <Link to="/settings" className="text-[#002FA7] hover:underline">Settings</Link>. We may suspend or terminate your access if you violate these Terms or if required by law. On termination, your data will be deleted in accordance with our <Link to="/privacy" className="text-[#002FA7] hover:underline">Privacy Policy</Link>.
                    </Block>

                    <Block h="12. Changes">
                        We may update these Terms from time to time. The "Last updated" date above reflects the most recent change. Continued use of the Service after a change constitutes acceptance of the new Terms.
                    </Block>

                    <Block h="13. Governing law">
                        These Terms are governed by the laws of India, without regard to conflict-of-law principles. Disputes will be resolved exclusively in the competent courts of Bengaluru, Karnataka.
                    </Block>

                    <Block h="14. Contact">
                        Questions about these Terms? Email <a href="mailto:legal@resumeforge.ai" className="text-[#002FA7] hover:underline">legal@resumeforge.ai</a> or use the <Link to="/contact" className="text-[#002FA7] hover:underline">contact form</Link>.
                    </Block>
                </div>
            </article>
            <Footer />
        </div>
    );
}

function Block({ h, children }) {
    return (
        <section>
            <h2 className="font-display text-xl font-semibold tracking-tight mb-3">{h}</h2>
            <div className="text-stone-800 leading-relaxed">{children}</div>
        </section>
    );
}
